interface TeamMember {
  name: string;
  roles: string[];
  year?: string;
  imageSrc: string;
}

const exec: TeamMember[] = [
  {
    name: "Samantha Shih",
    roles: ["Co-President"],
    year: "2028",
    imageSrc: "/people/samantha-shih.jpg",
  },
  {
    name: "Amy Lin",
    roles: ["Co-President"],
    year: "2029",
    imageSrc: "/people/amy-lin.png",
  },
  {
    name: "Nicole Zheng",
    roles: ["Marketing Chair", "Webmaster"],
    year: "2029",
    imageSrc: "/people/nicole-zheng.jpg",
  },
  {
    name: "Rebecca Xiong",
    roles: ["Finance Chair", "Outreach Chair"],
    year: "2028",
    imageSrc: "/people/rebecca-xiong.jpg",
  },
  {
    name: "Bridget Jiang",
    roles: ["Outreach Chair"],
    year: "2028",
    imageSrc: "/people/bridget-jiang.jpg",
  },
  {
    name: "Jany Zhang",
    year: "2030",
    roles: ["Outreach Chair"],
    imageSrc: "/people/temp-pic.jpg",
  },
  {
    name: "Sanchali Banerjee",
    roles: ["Events Chair"],
    year: "2029",
    imageSrc: "/people/sanchali-banerjee.jpeg",
  },
  {
    name: "Nyan Lin Htet",
    roles: ["Team Lead"],
    year: "2028",
    imageSrc: "/people/nyan-lin-htet.png",
  },
  {
    name: "Fela Ralte",
    roles: ["Team Lead"],
    year: "2028",
    imageSrc: "/people/fela-ralte.png",
  },
  {
    name: "Elisa Zhang",
    roles: ["Team Lead"],
    year: "2029",
    imageSrc: "/people/elisa-zhang.png",
  },
  {
    name: "Sophia Chen",
    roles: ["Team Lead"],
    year: "2030",
    imageSrc: "/people/sophia-chen.png",
  },
  {
    name: "Kaemyn Brown",
    roles: ["Team Lead"],
    year: "2030",
    imageSrc: "/people/kaemyn-brown.png",
  },
  {
    name: "Pedro Villafranco",
    roles: ["Team Lead"],
    year: "2030",
    imageSrc: "/people/pedro-villafranco.png",
  },
  {
    name: "Aryan Raj",
    roles: ["Team Lead"],
    year: "2030",
    imageSrc: "/people/aryan-raj.png",
  },
  {
    name: "Said Azaizah",
    roles: ["Team Lead"],
    year: "2030",
    imageSrc: "/people/said-azaizah.png",
  },
  {
    name: "Angelina Li",
    roles: ["Team Lead"],
    year: "2030",
    imageSrc: "/people/angelina-li.png",
  },
  {
    name: "Hailey Pan",
    roles: ["Advisor"],
    year: "2027",
    imageSrc: "/people/hailey-pan.jpg",
  },
];

const developers: string[] = [
  "Alyssa Chu",
  "Amelia Haller",
  "Amy Kuang",
  "Angelina Li",
  "Anna Nguyen",
  "Aryan Raj",
  "Carys Chan",
  "Ekam Kaur",
  "Elisa Zhang",
  "Ellie Strano",
  "Erick Chen",
  "Fela Ralte",
  "Jack Zhou",
  "Jany Zhang",
  "Jay Suarez Vanderpol",
  "Jovian Soejono",
  "Kaemyn Brown",
  "Kelvin La",
  "Marina Awad",
  "Natalia Arias",
  "Nicole Zheng",
  "Pedro Villafranco",
  "Said Azaizah",
  "Salim Siraj",
  "Sophia Chen",
];

interface PastTeam {
  semester: string;
  members: string[];
}

const pastTeams: PastTeam[] = [
  {
    semester: "Spring 2026",
    members: [
      "Adrian Johnson",
      "Alyssa Chu",
      "Amber Lin",
      "Angela Yang",
      "Anna Zavadski",
      "Carys Chan",
      "Charles Lai",
      "Connie Chen",
      "Daniel Jiang",
      "Giovanni Avila",
      "Jing Lin",
      "Jonathan Wang",
      "Julia Xiang",
      "Katherine Wang",
      "Kelvin La",
      "Megna Pillarisetti",
      "Neha Sane",
      "Nicole Zheng",
      "Riya Sahu",
      "Rojina Adhikari",
      "Serena Lu",
      "Sut Naw",
    ],
  },
  {
    semester: "Fall 2025",
    members: [
      "Akpandu Ekezie",
      "Amy Lin",
      "An Dinh",
      "Andy Yu",
      "April Kovacs",
      "Bhadra Rupesh",
      "Bridget Jiang",
      "Calista Huang",
      "Cindy Lin",
      "Daniel Jiang",
      "David Sevilla",
      "Elisa Zhang",
      "Ellie Feng",
      "Emma Li",
      "Harrison Liang",
      "Isabelle Chan",
      "Jada Ogueh",
      "Jerry Zhang",
      "Jieruei Chang",
      "Joanna Liu",
      "Josie Wang",
      "Katherine Wang",
      "Lin Ni",
      "Lucy Sun",
      "Maria Taveras",
      "Mohamed Algraiw",
      "Nicole Zheng",
      "Peter Lin",
      "Rahsun Komatsuzaki-Fields",
      "Riya Sahu",
      "Robert Chondro",
      "Samantha Shih",
      "Shelly Yang",
      "Thinh Pham",
      "Victoria Ou",
      "Yolanda Hu",
    ],
  },
  {
    semester: "Spring 2025",
    members: [
      "Alexander Liang",
      "An Dinh",
      "Anna Li",
      "Bhadra Rupesh",
      "Eric Zhan",
      "Fiona Lu",
      "Grant Hu",
      "Hailey Pan",
      "Jack MarionSims",
      "Jennet Zamanova",
      "Jensen Coonradt",
      "Jieruei Chang",
      "Jity Woldemichael",
      "Jocelyn Zhao",
      "Jocelyn Zheng",
      "Josie Wang",
      "Justin Le",
      "Kao Anchaleenukoon",
      "Kara Chou",
      "Michelle Sotelo",
      "Natalie Tan",
      "Owen Coulter",
      "Peter Lin",
      "Rachel Onwu",
      "Rahsun Komatsuzaki-Fields",
      "Samantha Shih",
      "Smruti Patil",
      "Stephen Hong",
      "Tolu Ojo-Osagie",
      "Victoria Park",
      "Vy Pham",
    ],
  },
  {
    semester: "Fall 2024",
    members: [
      "Andrew Yuan",
      "Andrew Zhang",
      "Angelina Ning",
      "Anna Li",
      "Bhadra Rupesh",
      "Elaine Jiang",
      "Eric Zhan",
      "Hailey Pan",
      "Jensen Coonradt",
      "Jocelyn Zheng",
      "Josie Wang",
      "Kathryn Le",
      "Khushi Parikh",
      "Lauren Yoo",
      "Nicole Shen",
      "Rahsun Komatsuzaki-Fields",
      "Samantha Shih",
      "Sejal Rathi",
      "Srilekha Mamidala",
    ],
  },
];

export { developers, exec, pastTeams };
